# Generated by Django 5.1.7 on 2025-04-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_category_women_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
